### PR TITLE
Started the Evaluation Screen

### PR DESCRIPTION
**Pull request by KarenMTan**
Add 'View Evaluation' button to Home screen to access Evaluation Screen. On the Evaluation Screen, added a video (with video controls). The video is accessed through its uri. On the bottom of the Evaluation screen, added timestamped comments. Also there are several warnings regarding invalid prop types and deprecated code warnings (because of the video control library). 
HomeScreen-AddViewEvalButton
EvaluationPage

### CODE REVIEW

**Review by leo-liu1 — COMMENTED** [review]
this looks good,nice work! liked how you broke up the evaluation screen into multiple components.

Here is my feedback (resubmit your pr after these changes are implemented):
 - remove src/screens/Evaluation/Post.js (i dont think this is used in your code)
 - it seems like EvaluationScreen does not pull data from Firebase currently, and the data that is displayed is hardcoded in. I think it would be best to create a doc with hardcoded values in firebase with the schema outlined in the notion, and hardcode the query in instead. (i.e. use Firebase().collection('evaluations').doc('[DOC_ID]').get().then(...) )

other than that, nice work!! thanks for submitting your pr

**Review by leo-liu1 — CHANGES_REQUESTED** [review]
forgot to request changes

**Comment by KarenMTan** [comment]
- Now able to view comments from Firestore (given an evaluation DocumentID)
- Created a button to access the "Create Evaluation" Screen
- Clicking "Create" updates the evaluations array on Firestore 
- There are some preliminary error checks 

AddedComment
CreateEvaluation
EvaluationScreen
Alert1
Alert2

**Review by KarenMTan — COMMENTED** [review]
See previous note ^

**Review by leo-liu1 — APPROVED** [review]
looks good! nice work karen 🔥

**Pull request merged**
